'use strict';

// SessionStart hook. Injects the canonical release context so a session starts
// from verified repository state instead of from whatever it can infer.
//
// It is strictly read-only and strictly optional: any failure produces no
// output at all rather than a broken session. A context injector that can
// block a session is worse than no context injector.

const path = require('node:path');

const ROOT = path.resolve(__dirname, '..', '..');

function buildContext() {
  const core = require(path.join(ROOT, 'scripts', 'release', 'release-core.cjs'));
  const deps = core.createDeps({ repositoryRoot: ROOT });
  const lines = ['Release harness context (generated by .claude/hooks/release-context.cjs):'];

  const head = deps.runCommand('git', ['rev-parse', 'HEAD'], { cwd: ROOT, timeoutMs: 10000 });
  const branch = deps.runCommand('git', ['branch', '--show-current'], { cwd: ROOT, timeoutMs: 10000 });
  if (head && head.status === 0) {
    lines.push(`- Branch ${String(branch && branch.stdout || 'HEAD').trim() || 'HEAD'} at ${String(head.stdout).trim()}`);
  }

  try {
    const backlog = core.loadBacklog(deps);
    const selection = core.selectNextTask(backlog);
    if (selection.selected) {
      lines.push(`- Next release task: ${selection.selected.id} — ${selection.selected.title} (${selection.selected.severity})`);
      lines.push(`- Eligible order: ${selection.rankedIds.join(' > ')}`);
    } else {
      lines.push('- Next release task: none eligible. Run node scripts/release/release.cjs plan for the exclusions.');
    }
  } catch (error) {
    lines.push(`- Backlog unavailable: ${core.redact(error && error.message || error)}`);
  }

  const mode = String(process.env.RELEASE_HARNESS_MODE || '').trim();
  lines.push(mode
    ? `- A release run is active (RELEASE_HARNESS_MODE=${mode}). Product-code and harness edits are denied for its duration.`
    : '- No release run is active. Ordinary feature work is allowed; production actions are not.');
  lines.push('- The harness halts at gate G7. No agent performs a production action: no push, tag, release, db push, function deploy, or publish.');
  lines.push('- release/approvals/ is human-only and is denied to agents in every mode.');
  lines.push('- Read AGENTS.md and docs/release-harness.md before a release run.');
  return lines.join('\n');
}

function main(streams = process) {
  try {
    streams.stdout.write(`${JSON.stringify({
      hookSpecificOutput: {
        hookEventName: 'SessionStart',
        additionalContext: buildContext()
      }
    })}\n`);
  } catch {
    // Deliberately silent: context is a convenience, never a gate.
  }
  return 0;
}

module.exports = Object.freeze({ buildContext, main });

if (require.main === module) {
  process.exitCode = main();
}
