param([switch]$StartSupabase,[switch]$IncludeRuntime,[switch]$Json,[string]$ReportPath)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot 'common.ps1')
$results=New-Object Collections.Generic.List[object];$configurationError=$false
try{$root=Get-GitRoot}catch{$root=(Get-Location).Path;$configurationError=$true;$results.Add((New-CheckResult 'Git repository' 'Failed' $true 0 $_.Exception.Message 'git rev-parse --show-toplevel'))}
if(-not$configurationError){
  $isDashboard=(Split-Path ([IO.Path]::GetFullPath($root).TrimEnd('\','/')) -Leaf)-eq'dashboard';$results.Add((New-CheckResult 'Dashboard repository' $(if($isDashboard){'Passed'}else{'Failed'}) $true 0 $root ''))
  foreach($tool in @(@('Git','git',$true),@('Node','node',$true),@('npm','npm.cmd',$true),@('PowerShell','powershell.exe',$true),@('Docker CLI','docker',$false),@('Supabase CLI','npx.cmd',$false))){$ok=Test-CommandAvailable $tool[1];$results.Add((New-CheckResult $tool[0] $(if($ok){'Passed'}elseif($tool[2]){'Failed'}else{'Warning'}) ([bool]$tool[2]) 0 $(if($ok){'Available'}else{'Not found'}) $tool[1]))}
  $branch=Get-CurrentBranch;$results.Add((New-CheckResult 'Git branch' 'Passed' $true 0 $branch 'git branch --show-current'));$porcelain=@(& git status --porcelain);$conflicts=@(& git diff --name-only --diff-filter=U)
  $results.Add((New-CheckResult 'Merge conflicts' $(if($conflicts.Count){'Failed'}else{'Passed'}) $true 0 ($conflicts-join', ') 'git diff --name-only --diff-filter=U'));$results.Add((New-CheckResult 'Working tree' $(if($porcelain.Count){'Warning'}else{'Passed'}) $false 0 $(if($porcelain.Count){"$($porcelain.Count) changed path(s)"}else{'Clean'}) 'git status --porcelain'));$results.Add((Invoke-CheckedCommand 'Remote connectivity' 'git' @('ls-remote','--exit-code','origin','HEAD') $false 30 $root))
  foreach($path in @('package.json','package-lock.json','supabase/config.toml','supabase/migrations','scripts/check-atomic-writes.ps1','scripts/check-runtime-smoke-harness.ps1','scripts/check-team-management.ps1')){$exists=Test-Path -LiteralPath(Join-Path $root $path);$results.Add((New-CheckResult "Project: $path" $(if($exists){'Passed'}else{'Failed'}) $true 0 $(if($exists){'Present'}else{'Missing'}) ''))}
  $quality=@(@('Unit tests','npm.cmd',@('test'),300),@('JavaScript syntax','npm.cmd',@('run','check:js'),180),@('Secret scan','npm.cmd',@('run','check:secrets'),180),@('Atomic SQL structure','powershell.exe',@('-NoProfile','-ExecutionPolicy','Bypass','-File','scripts/check-atomic-writes.ps1'),120),@('Runtime harness structure','powershell.exe',@('-NoProfile','-ExecutionPolicy','Bypass','-File','scripts/check-runtime-smoke-harness.ps1'),120),@('Team management structure','powershell.exe',@('-NoProfile','-ExecutionPolicy','Bypass','-File','scripts/check-team-management.ps1'),120),@('Whitespace','git',@('diff','--check'),60));foreach($check in $quality){$results.Add((Invoke-CheckedCommand $check[0] $check[1] $check[2] $true $check[3] $root))}
  $results.Add((Invoke-CheckedCommand 'Docker daemon' 'docker' @('info','--format','{{.ServerVersion}}') $false 30 $root));if($StartSupabase){$results.Add((Invoke-CheckedCommand 'Supabase start' 'npx.cmd' @('supabase','start') $true 180 $root))};$results.Add((Invoke-CheckedCommand 'Supabase status' 'npx.cmd' @('supabase','status') ([bool]($StartSupabase-or$IncludeRuntime)) 45 $root));if($IncludeRuntime){$results.Add((Invoke-CheckedCommand 'Runtime smoke' 'powershell.exe' @('-NoProfile','-ExecutionPolicy','Bypass','-File','scripts/dev/smoke.ps1') $true 600 $root))}
}
$exitCode=Get-ToolchainExitCode $results -ConfigurationError:$configurationError;$resultArray=@($results|ForEach-Object{$_});$payload=[pscustomobject]@{Ready=($exitCode-eq 0);ExitCode=$exitCode;Branch=$(if($configurationError){$null}else{$branch});Results=$resultArray};if($ReportPath){Write-ToolchainReport $payload $ReportPath -Json:$Json -GitRoot $root};if($Json){$payload|ConvertTo-Json -Depth 8}else{Show-CheckSummary $results;if($exitCode-eq 0){Write-Host 'READY FOR DEVELOPMENT' -ForegroundColor Green}else{Write-Host 'BLOCKED' -ForegroundColor Red}};exit $exitCode
