param([string]$BaseBranch='main',[switch]$RunPreflight,[switch]$Json,[string]$ReportPath='artifacts/review.md')
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
. (Join-Path $PSScriptRoot 'common.ps1')
$root=Get-GitRoot;$branch=Get-CurrentBranch
if($RunPreflight){$pre=Invoke-CheckedCommand 'Preflight' 'powershell.exe' @('-NoProfile','-ExecutionPolicy','Bypass','-File','scripts/dev/preflight.ps1','-Json') $true 600 $root;if($pre.Status-eq'Failed'){throw "Preflight blocked review: $($pre.Details)"}}
$baseRef=Resolve-GitBaseRef $BaseBranch;$mergeBase=Get-GitMergeBase $baseRef.Requested $baseRef.Resolved
$status=@(& git status --short);$commits=@(& git log --oneline "$mergeBase..HEAD");$trackedChanged=@(& git diff --name-only $mergeBase);$untracked=@(& git ls-files --others --exclude-standard);$changed=@($trackedChanged+$untracked|Sort-Object -Unique);$stat=(& git diff --stat $mergeBase|Out-String).Trim();$diff=(& git diff --no-ext-diff --unified=0 $mergeBase|Out-String);foreach($file in $untracked){$full=Join-Path $root $file;if(Test-Path -LiteralPath $full -PathType Leaf){$diff+="`n"+((Get-Content -LiteralPath $full|ForEach-Object{"+$_"})-join"`n")}}
$dbRelevant=@($changed|Where-Object{$_-like'supabase/migrations/*'-or$_-like'*.sql'});$securityRelevant=@($changed|Where-Object{$_-like'supabase/*'-or$_-like'src/*'-or$_-eq'index.html'});$businessRelevant=@($changed|Where-Object{$_-like'src/*'-or$_-like'supabase/*'-or$_-eq'index.html'})
function Get-RelevantDiff([string[]]$Files){$text='';foreach($file in $Files){if($untracked-contains$file){$full=Join-Path $root $file;if(Test-Path -LiteralPath $full -PathType Leaf){$text+="`n"+((Get-Content -LiteralPath $full|ForEach-Object{"+$_"})-join"`n")}}else{$text+="`n"+(& git diff --no-ext-diff --unified=0 $mergeBase -- $file|Out-String)}};return $text}
$dbDiff=Get-RelevantDiff $dbRelevant;$securityDiff=Get-RelevantDiff $securityRelevant;$businessDiff=Get-RelevantDiff $businessRelevant
$security=@();$database=@();$risks=@();$manual=@()
function Add-Match([string]$Text,[string]$Pattern,[string]$Message,[Collections.Generic.List[string]]$Target){if($Text-match$Pattern){$Target.Add($Message)}}
$securityList=New-Object Collections.Generic.List[string];$dbList=New-Object Collections.Generic.List[string]
Add-Match $securityDiff '(?im)^\+.*(?:SECURITY DEFINER|CREATE POLICY|ALTER POLICY|GRANT |REVOKE |ROW LEVEL SECURITY)' 'Authorization, RLS, grants, or SECURITY DEFINER changed.' $securityList
Add-Match $securityDiff '(?im)^\+.*(?:service_role|safeCodes|DATABASE_|AUTH_REQUIRED|ADMIN_REQUIRED)' 'Auth, elevated access, or error mapping changed.' $securityList
$destructivePattern='(?im)^\+.*(?:D'+'ROP\s+(?:DATABASE|TABLE|SCHEMA)|TRUNCATE|DELETE\s+FROM)'
Add-Match $dbDiff $destructivePattern 'Potentially destructive SQL added.' $dbList
Add-Match $dbDiff '(?im)^\+.*(?:CREATE|ALTER|DROP)\s+(?:TABLE|FUNCTION|TYPE|INDEX|POLICY)' 'Database definition changed.' $dbList
$migrationFiles=@($changed|Where-Object{$_-like'supabase/migrations/*'});if($migrationFiles.Count){$dbList.Add("Migration files changed: $($migrationFiles-join', ')")}
if($businessDiff-match'(?im)^\+.*(?:TODO|FIXME|HACK)'){$risks+='New TODO/FIXME/HACK marker.'};if($businessDiff-match'(?im)^\+.*(?:new|assigned|in_work|no_answer|success|failed)'){$manual+='Review business status rules.'};if($securityList.Count){$manual+='Security-sensitive diff requires manual review.'};if($dbList.Count){$manual+='Database changes require migration and rollback review.'}
$packageChanged=@($changed|Where-Object{$_-in@('package.json','package-lock.json')});$tests=@($changed|Where-Object{$_-like'tests/*'});$docs=@($changed|Where-Object{$_-like'docs/*'-or$_-eq'README.md'});$added=0;$deleted=0;foreach($line in @(& git diff --numstat $mergeBase)){if($line-match'^(\d+)\s+(\d+)'){ $added+=[int]$Matches[1];$deleted+=[int]$Matches[2] }};foreach($file in $untracked){$full=Join-Path $root $file;if(Test-Path -LiteralPath $full -PathType Leaf){$added+=(Get-Content -LiteralPath $full).Count}}
$recommendation=if($dbList|Where-Object{$_-like'Potentially destructive*'}){'BLOCKED'}elseif($securityList.Count-or$dbList.Count-or$status.Count){'REVIEW WITH WARNINGS'}else{'READY FOR REVIEW'}
$payload=[ordered]@{Title='Review report';Scope=[ordered]@{CurrentBranch=$branch;BaseBranch=$BaseBranch;ResolvedBaseRef=$baseRef.Resolved;MergeBase=$mergeBase;Commits=$commits};GitState=$status;ChangedFiles=$changed;DiffStat=$stat;SecuritySensitiveChanges=@($securityList);DatabaseChanges=@($dbList);Tests=$tests;Documentation=$docs;PackageFiles=$packageChanged;DiffSize=[ordered]@{Added=$added;Deleted=$deleted};Risks=$risks;RequiredManualReview=$manual;Recommendation=$recommendation}
$statusLines=if($status.Count){@($status|ForEach-Object{"- ``$_``"})}else{@('- Clean')};$changedLines=if($changed.Count){@($changed|ForEach-Object{"- ``$_``"})}else{@('- None')};$securityLines=if($securityList.Count){@($securityList|ForEach-Object{"- $_"})}else{@('- None detected')};$dbLines=if($dbList.Count){@($dbList|ForEach-Object{"- $_"})}else{@('- None detected')};$testLines=if($tests.Count){@($tests|ForEach-Object{"- ``$_``"})}else{@('- No test files changed')};$riskLines=if($risks.Count){@($risks|ForEach-Object{"- $_"})}else{@('- No automated risk marker')};$manualLines=if($manual.Count){@($manual|ForEach-Object{"- $_"})}else{@('- Normal reviewer verification')}
$md=(@("# Review report","","## Scope","- Current branch: ``$branch``","- Base branch: ``$BaseBranch``","- Resolved base ref: ``$($baseRef.Resolved)``","- Merge base: ``$mergeBase``","- Diff size: +$added / -$deleted","","## Git state")+$statusLines+@("","## Changed files")+$changedLines+@("","## Security-sensitive changes")+$securityLines+@("","## Database changes")+$dbLines+@("","## Tests")+$testLines+@("","## Risks")+$riskLines+@("","## Required manual review")+$manualLines+@("","## Recommendation","**$recommendation**"))-join"`n"
if($ReportPath){Write-ToolchainReport $(if($Json){[pscustomobject]$payload}else{$md}) $ReportPath -Json:$Json -GitRoot $root};if($Json){[pscustomobject]$payload|ConvertTo-Json -Depth 8}else{Write-Host $md};if($recommendation-eq'BLOCKED'){exit 1};exit 0
